---
title: Hiree
email: your-email@hiree.app
description: ''
baseurl: 'https://wetcouch.github.io/hiree-landing/'
url: https://hiree.app
twitter_username: jekyllrb
github_username: jekyll
plugins:
- jekyll-feed
collections:
  pages:
    output: true
